# _data/schema.yml

- x-default: /mul/schema/ISO-639-3
  gid: XZ
  namen: ISO 639-3
  hashtag: schema-XZ-ISO-639-3

- x-default: /mul/schema/ISO-639-3
  gid: XZ
  namen: ISO 15924
  hashtag: schema-XZ-ISO-15924

