swagger: "2.0"
info:
  title: COD Services API
  version: v2
host: beta.itos.uga.edu
basePath: /CODV2API/api/v1
schemes:
  - https
paths:
  /locations:
    x-amf-description: |
      List available locations(with metadata about each such as preferred name, iso codes, etc.) and lists of themes available in each location Returns: location name, iso_3, themes
    get:
      responses: {}
  /locations/{pCode}:
    x-amf-description: |
      Location-level Listing of all themes and versions available for a location. LocationId in this case, represents the P-Code. P-Code representing a specific location. It is case insensitive.JSON
    parameters:
      -
        name: pCode
        required: true
        in: path
        type: string
    get:
      responses: {}
  /themes: {}
  /themes/cod-ab: {}
  /themes/cod-ab/locations: {}
  /themes/cod-ab/locations/{pCode}:
    parameters:
      -
        name: pCode
        required: true
        in: path
        type: string
  /themes/cod-ab/locations/{pCode}/versions:
    parameters:
      -
        name: pCode
        required: true
        in: path
        type: string
    get:
      description: Provides metadata about a specific COD-AB version (number of levels, level names, notes about levels, number of units within each level, availability of geometry, version dates, etc.) with URLs to various downloadables and services. example
      responses: {}
  /themes/cod-ab/locations/{pCode}/versions/{versionId}: {}
