#%RAML 1.0

title: COD Version 2 API
version: v2v1
baseUri: https://beta.itos.uga.edu/CODV2API/api/v1
mediaType: [ application/json]
# mediaType: [ application/json, application/xml ]

# https://beta.itos.uga.edu/CODV2API/Help

get: /locations
description: >-
  List available locations(with metadata about each such as preferred name,
  iso codes, etc.) and lists of themes available in each location
  Returns: location name, iso_3, themes
body:
  type:
  example:
responses:
  200:
    description: There are no errors, the request has been successful
    body: 
  404:
    description: The server has not found anything matching the request URI
    body:
      type: ErrorSchema