# FILE:            .github/workflows/05-deploy-github-pages.yml
#
# @see https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
# @see https://github.com/marketplace/actions/github-pages-action

name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bash systema/infrastructuram/travis-ci.sh

      # @see https://github.com/actions/setup-java#supported-distributions
      - name: "Java installation (required by openapi-generator-cli)"
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      # @see https://github.com/actions/setup-node
      - name: "Node/NPM installation (required by openapi-generator-cli)"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: "npm install -g @openapitools/openapi-generator-cli"
        run: npm install -g @openapitools/openapi-generator-cli

      - name: "openapi-generator-cli: generate files"
        run: bash ./systema/programma/openapi-exportandum.sh

      - name: "Steps before Jekyll: CNAME"
        run: |
          echo "hapi.etica.ai" > ./CNAME

      - name: "DEBUG: sudo apt install tree"
        run: sudo apt install tree

      - name: "DEBUG: tree"
        run: tree

        # run: make ci
      - name: Deploy to HXL-CPLP/hapi.etica.ai
        uses: peaceiris/actions-gh-pages@v3
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          external_repository: HXL-CPLP/hapi.etica.ai
          publish_branch: gh-pages
          publish_dir: "./"
          destination_dir: ./docs
          enable_jekyll: true
          # cname: hapi.etica.ai
    # - name: Deploy
    #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./out
