# Veja https://github.com/HXL-CPLP/Auxilium-Humanitarium-API/issues/12

# @TODO: https://www.adrianbolonio.com/en/accessibility-github-actions/
# @TODO: https://github.com/pa11y/pa11y

name: Audit live site (lighthouse)
on:
  push:
    branches:
      - main

jobs:
  audit:
    needs: deploy-github-pages
    runs-on: ubuntu-latest
    steps:

    - name: Audit live URL, https://hapi.etica.ai/
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://hapi.etica.ai/'

    - name: Audit live URL, https://hapi.etica.ai/por/
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://hapi.etica.ai/por/'

    # - name: Audit live URL, https://hapi.etica.ai/por-Latn/
    #   uses: jakejarvis/lighthouse-action@master
    #   with:
    #     url: 'https://hapi.etica.ai/por-Latn/'

    - name: Audit live URL, https://hapi.etica.ai/api/UN/HDX/eng/
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://hapi.etica.ai/api/UN/HDX/eng/'

    - name: Audit live URL, https://hapi.etica.ai/eng-Latn/api/UN/reliefweb/
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://hapi.etica.ai/eng-Latn/api/UN/reliefweb/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'


# ____________________________________________________________________________ #
#### _[por] Como executar localmente o lighthouse [por]_
## @see https://developers.google.com/web/tools/lighthouse/
# npm install -g lighthouse
#

# lighthouse https://hapi.etica.ai/
# lighthouse https://hapi.etica.ai/por/
# # lighthouse https://hapi.etica.ai/por-Latn/
# lighthouse https://hapi.etica.ai/eng-Latn/api/UN/reliefweb/
#
# lighthouse http://127.0.0.1:4000/ --output-path=./_systema/lighthouse-reports/home.html
# lighthouse http://127.0.0.1:4000/por/ --output-path=./_systema/lighthouse-reports/por.html
# # lighthouse http://127.0.0.1:4000/por-Latn/ --output-path=./_systema/lighthouse-reports/por-Latn.html
# lighthouse http://127.0.0.1:4000/eng-Latn/api/UN/reliefweb/ --output-path=./_systema/lighthouse-reports/eng-Latn__api__UN__reliefweb.html

#### _[por] Como executar localmente o pa11y [por]_
## @see https://github.com/pa11y/pa11y
# npm install -g pa11y
#

# pa11y https://hapi.etica.ai/
# pa11y https://hapi.etica.ai/por/
# pa11y https://hapi.etica.ai/eng-Latn/api/UN/reliefweb/

# pa11y http://127.0.0.1:4000/
# pa11y http://127.0.0.1:4000/por/
# pa11y http://127.0.0.1:4000/eng-Latn/api/UN/reliefweb/
