# ARQUIVO:         _data/por/l10n.yml

# Trivia:
#  - "applicātiōnem"
#     - https://en.wiktionary.org/wiki/applicatio#Latin
#  - "programma"
#     - https://en.wiktionary.org/wiki/programma#Italian
#  - "interface", inter- (“between”) +‎ face (“shape, figure, form”).
#     - "inter"
#       - https://en.wiktionary.org/wiki/inter-#Latin
#     - "faciem"
#       - https://en.wiktionary.org/wiki/facies#Latin
l10n_API: "API"

# - 'Reserved directly by ISO 3166/MA for the United Nations'
#   - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations
l10n_API_UN: "API UN 🇺🇳"

# - 'XZ'
#   - 'UN/LOCODE assigns XZ to represent installations in international waters.[7]'
# '🌐'
#   - https://emojipedia.org/globe-with-meridians/
l10n_API_XZ: "API XZ 🌐"

l10n_API_BR: "API BR 🇧🇷"

# - 'schema'
#   - https://en.wiktionary.org/wiki/schema#Latin
l10n_schema: "Schēmam"

# - 'fīlum'
#   - https://en.wiktionary.org/wiki/filum
l10n_openapi_filum: "OpenAPI Fīlum"

# - Vicipaediam
#   - https://la.wikipedia.org/wiki/Vicipaedia:Pagina_prima
l10n_vicipaediam: "Vicipaediam"
